title: Chess openings
email: s.wisniewski1101@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  List of popular chess openings with images
  and short descriptions.
baseurl: "" # the subpath of your site, e.g. /blog
domain: h3xoo.github.io
url: https://h3xoo.github.io
github_username:  h3xOo

markdown: kramdown

collections:
  openings:
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
