title: Chess openings
email: s.wisniewski1101@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
domain: h3xoo.github.io
url: https://h3xoo.github.io
github_username:  h3xOo

markdown: kramdown

collections:
  openings:
    output: true
    permalink: "/:collection/:title"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# relative_links:
#   enabled:     true
#   collections: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
